# Generated by Django 5.2.4 on 2025-07-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiya', models.CharField(max_length=255)),
                ('telefon_raqam', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dori_nomi', models.CharField(max_length=255)),
                ('narxi', models.FloatField()),
                ('ikpu', models.CharField(max_length=50)),
                ('image_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorixona_nomi', models.CharField(max_length=255)),
                ('manzil', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=50)),
                ('dorixona_egasi', models.CharField(max_length=255)),
                ('kontrakt', models.CharField(max_length=50)),
                ('dagovor', models.CharField(max_length=50)),
                ('rs', models.CharField(max_length=50)),
                ('mfo', models.CharField(max_length=50)),
            ],
        ),
    ]
