# Generated by Django 5.2.4 on 2025-07-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_column='employee_id', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ism_familiya',
            field=models.CharField(db_column='ism_familiya', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telefon_raqam',
            field=models.CharField(db_column='telefon_raqam', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dori_nomi',
            field=models.CharField(db_column='dori_nomi', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='ikpu',
            field=models.CharField(db_column='ikpu', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image_file_id',
            field=models.CharField(blank=True, db_column='image_file_id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='info',
            field=models.TextField(blank=True, db_column='info', null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='narxi',
            field=models.FloatField(db_column='narxi'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='dagovor',
            field=models.CharField(db_column='dagovor', max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='dorixona_egasi',
            field=models.CharField(db_column='dorixona_egasi', max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='dorixona_nomi',
            field=models.CharField(db_column='dorixona_nomi', max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='inn',
            field=models.CharField(db_column='inn', max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='kontrakt',
            field=models.CharField(db_column='kontrakt', max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='manzil',
            field=models.CharField(db_column='manzil', max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='mfo',
            field=models.CharField(db_column='mfo', max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='rs',
            field=models.CharField(db_column='rs', max_length=50),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='xodimlar',
        ),
        migrations.AlterModelTable(
            name='medicine',
            table='dorilar',
        ),
        migrations.AlterModelTable(
            name='pharmacy',
            table='dorixonalar',
        ),
    ]
